version: '3'
services:
  web:
    volumes:
      - '../../../app:/opt/node_app/app'
      - '../../../lib:/opt/node_app/lib'
      - '../../../views:/opt/node_app/views'
      - '../../../public:/opt/node_app/public'
      - '../../../extensions:/opt/node_app/extensions'
      - '../../../db:/opt/node_app/db'
      - '../../../certs:/opt/node_app/certs'
    ports:
      - '8100:3000'
    restart: 'always'
    stdin_open: true
    tty: true
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/Development-lokal/web/Dockerfile'
    depends_on:
      - 'db'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
  db:
    image: 'mariadb:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'eefTmWJE'
      MYSQL_DATABASE: 'traxit'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'w4kehb9J'
    volumes:
      - './db_init:/docker-entrypoint-initdb.d'
    ports:
      - '9906:3306'
    restart: 'always'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
